<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('guru')->insert([
            [
                'nip' => '198001012005011001',
                'nama' => 'A Rhmad Hidayat, S.Pd.',
                'jabatan' => 'Kepala Sekolah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198102022006012002',
                'nama' => 'Nuraeni, S.Pd.',
                'jabatan' => 'Guru Matematika',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198203032007011003',
                'nama' => 'Ela Haryati, S.Pd.',
                'jabatan' => 'Guru Matematika',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198304042008012004',
                'nama' => 'Habib Suhandar, S.Pd.',
                'jabatan' => 'Guru Pendidikan Pancasila& Sejarah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198405052009011005',
                'nama' => 'Nopi Yanti, S.Pd.',
                'jabatan' => 'Guru Pendidikan Pancasila & Sejarah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198506062010012006',
                'nama' => 'Jaya Nur Setiawan, S.Pd.',
                'jabatan' => 'Guru Pjok & Bahasa Sunda',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198607072011011007',
                'nama' => ' Setiawan, S.E.',
                'jabatan' => 'Guru Pemasan',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198708082012012008',
                'nama' => 'Rahmat Setiawan, S.T.I.',
                'jabatan' => 'Guru Pplg',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198809092013011009',
                'nama' => 'Dini Andrian, S.E.',
                'jabatan' => 'Guru Pemasaran',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198910102014012010',
                'nama' => 'Emi Resmiyati, S.Pd.',
                'jabatan' => 'Guru Projek Ilmu Pengetahuan Alam & Sosial',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198011112005011011',
                'nama' => 'Rina Susana, S.Pd.',
                'jabatan' => 'Guru Basaha Ingggris',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198112122006012012',
                'nama' => 'Jajang Ridwan, S.T.',
                'jabatan' => 'Guru Teknik Otomotif',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198201132007011013',
                'nama' => 'Yani Cahyani, S.Pd.',
                'jabatan' => 'Guru Bahasa Inggris',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198302142008012014',
                'nama' => 'Mega Nurunnisa, S.Pd.',
                'jabatan' => 'Guru Bahasa Indonesia & Seni Budaya',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198504162010012016',
                'nama' => 'Mia Rusmiati, S.Pd.',
                'jabatan' => 'Guru Matematika & Bahasa Inggris',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198706182012012018',
                'nama' => 'Silvi Danu Respita, S.T.',
                'jabatan' => 'Guru Pplg',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198807192013011019',
                'nama' => 'Siti Rahmawati, S.PDP.I',
                'jabatan' => 'Guru Pai.Bp',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198908202014012020',
                'nama' => 'Ai Nurhasanah, S.Pd.',
                'jabatan' => 'Guru Matematika & Informatika',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198009212005011021',
                'nama' => 'Isnan Wiranursyeha, S.Pd.I.',
                'jabatan' => 'Guru Bahasa Indonesia',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198110222006012022',
                'nama' => 'Bani faudoly, S.Pd.',
                'jabatan' => 'Guru Pplg ',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198211232007011023',
                'nama' => 'Didi Mei Somantri, S.KOM.',
                'jabatan' => 'Guru Pplg',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198312242008012024',
                'nama' => 'Budiana Hermawan, S.TP.',
                'jabatan' => 'Guru Aphp',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198401252009011025',
                'nama' => 'Edeh Kurniasih, S.Pd.',
                'jabatan' => 'Guru Bahasa Indonesia',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198502262010012026',
                'nama' => 'Romi Darmayadi, S.Pd.S.T',
                'jabatan' => 'Guru Teknik Otomotif',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198603272011011027',
                'nama' => 'Eli Maryammah, S.Pd.',
                'jabatan' => 'Guru Pemasaran',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198704282012012028',
                'nama' => 'Nanang suryana, SE.,M.M.',
                'jabatan' => 'Guru Pemasaran',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198805292013011029',
                'nama' => 'Indra Priatna, S.Pd.',
                'jabatan' => 'Guru Pendidikan Pancasila & Informatika',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198906302014012030',
                'nama' => 'Indra Murgianto, S.Pd.',
                'jabatan' => 'Guru Pemasaran',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '98906302014012033',
                'nama' => 'Didi Sukardi, S.Pd.',
                'jabatan' => 'Guru Pjok',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '98906302014012037',
                'nama' => 'Asep Muhlis Sulaeman, S.Pd.I',
                'jabatan' => 'Guru Pai. Bp',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198209022007011033',
                'nama' => 'Yayup Hindriyani, S.Pd.',
                'jabatan' => 'Guru Matematika & Informatika',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198310032008012034',
                'nama' => 'Wahyudin, S.TR.KOM.',
                'jabatan' => 'Guru Pplg',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198411042009011035',
                'nama' => 'Kamalia, SE.',
                'jabatan' => 'Guru Pemasaran',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198512052010012036',
                'nama' => 'Andri Muhoir, S.T.',
                'jabatan' => 'Guru Teknik Otomotif',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198613062011011037',
                'nama' => 'Moch Yoga Agung N, S.Pd.M.PD.',
                'jabatan' => 'Guru Bahasa Sunda',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198714072012012038',
                'nama' => 'Ende Iskandar, S.TP.',
                'jabatan' => 'Guru Aphp',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198815082013011039',
                'nama' => 'Santi Mustika,',
                'jabatan' => 'Laboran Pemasaran',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198916092014012040',
                'nama' => 'Moch Najib,',
                'jabatan' => 'Laboran Pplg',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198017102005011041',
                'nama' => 'Ahmad Suhendra,',
                'jabatan' => 'Kebersihan & Keindahan Sekolah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198118112006012042',
                'nama' => 'D Jamaludin,',
                'jabatan' => 'Kebersihan & Keindahan Sekolah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198219122007011043',
                'nama' => 'Apendi,',
                'jabatan' => 'Kebersihan & Keindahan Sekolah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198320132008012044',
                'nama' => 'Tatang Rustandi,',
                'jabatan' => 'Kebersihan & Keindahan Sekolah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198421142009011045',
                'nama' => 'Yogi Saputra,',
                'jabatan' => 'Kebersihan & Keindahan Sekolah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198522152010012046',
                'nama' => 'Muldiansah,',
                'jabatan' => 'Kebersihan & Keindahan Sekolah',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198623162011011047',
                'nama' => 'Nurdiansah, S.IP.',
                'jabatan' => 'Adm Persatuan, Kesiswaan & Kurikulum',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198724172012012048',
                'nama' => 'Sima Kristina, S.KOM.',
                'jabatan' => 'Adm Keuangan Dan Publikasi',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198825182013011049',
                'nama' => 'Sakti Alamsayah,.SE.',
                'jabatan' => 'Administrasi Sarpras',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198926192014012050',
                'nama' => 'Ayi Suryati. A. MA. PUST.,',
                'jabatan' => 'Guru Biologi',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198027202005011051',
                'nama' => 'Nurah Alwaini, A.MA.PUST.',
                'jabatan' => 'Guru Fisika',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198128212006012052',
                'nama' => 'Ramdan Bastaman,..',
                'jabatan' => 'Administrasi Sarpras',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198229222007011053',
                'nama' => 'Saripul Basar,',
                'jabatan' => 'Laboran Aphp',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '198330232008012054',
                'nama' => 'Asep Purnama,',
                'jabatan' => 'Laboran Teknik Otomotif',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
            
            ],
        ]);
    }
}
